rules:
  quotes:
    - 1
    - style: "double"
  leading-zero:
    - 1
    - include: true
  border-zero:
    - 1
    - convention: "none"
  shorthand-values:
    - 1
    - allowed-shorthands: [1, 2]
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-qualifying-elements: 0
  class-name-format:
    - 1
    - convention: "hyphenatedbem"
  placeholder-name-format:
    - 1
    - convention: "hyphenatedbem"
  placeholder-in-extend: 0
  property-sort-order:
    - 1
    - order:
        - "content"
        - "all"
        - "position"
        - "z-index"
        - "left"
        - "right"
        - "top"
        - "bottom"
        - "isolation"
        - "display"
        - "flex-flow"
        - "flex-direction"
        - "flex-wrap"
        - "justify-content"
        - "align-content"
        - "align-items"
        - "order"
        - "flex"
        - "flex-basis"
        - "flex-grow"
        - "flex-shrink"
        - "align-self"
        - "float"
        - "clear"
        - "overflow"
        - "overflow-x"
        - "overflow-y"
        - "appearance"
        - "user-select"
        - "box-sizing"
        - "orientation"
        - "zoom"
        - "min-zoom"
        - "max-zoom"
        - "user-zoom"
        - "size"
        - "width"
        - "max-width"
        - "min-width"
        - "height"
        - "max-height"
        - "min-height"
        - "object-position"
        - "object-fit"
        - "resize"
        - "break-inside"
        - "break-before"
        - "break-after"
        - "page-break-inside"
        - "page-break-before"
        - "page-break-after"
        - "margin"
        - "margin-left"
        - "margin-right"
        - "margin-top"
        - "margin-bottom"
        - "padding"
        - "padding-left"
        - "padding-right"
        - "padding-top"
        - "padding-bottom"
        - "table-layout"
        - "list-style"
        - "list-style-position"
        - "list-style-type"
        - "list-style-image"
        - "border"
        - "border-collapse"
        - "border-style"
        - "border-width"
        - "border-color"
        - "border-left"
        - "border-left-style"
        - "border-left-width"
        - "border-left-color"
        - "border-right"
        - "border-right-style"
        - "border-right-width"
        - "border-right-color"
        - "border-top"
        - "border-top-style"
        - "border-top-width"
        - "border-top-color"
        - "border-bottom"
        - "border-bottom-style"
        - "border-bottom-width"
        - "border-bottom-color"
        - "border-radius"
        - "border-top-left-radius"
        - "border-top-right-radius"
        - "border-bottom-left-radius"
        - "border-bottom-right-radius"
        - "outline"
        - "outline-offset"
        - "outline-style"
        - "outline-width"
        - "outline-color"
        - "box-shadow"
        - "vertical-align"
        - "writing-mode"
        - "direction"
        - "unicode-bidi"
        - "font"
        - "font-family"
        - "font-size"
        - "font-style"
        - "font-weight"
        - "font-stretch"
        - "font-kerning"
        - "font-variant"
        - "font-variant-position"
        - "font-variant-caps"
        - "font-variant-numeric"
        - "font-variant-alternates"
        - "font-variant-ligatures"
        - "font-variant-east-asian"
        - "font-feature-settings"
        - "line-height"
        - "quotes"
        - "text-align"
        - "text-indent"
        - "text-transform"
        - "text-overflow"
        - "text-decoration"
        - "text-decoration-line"
        - "text-decoration-style"
        - "text-decoration-color"
        - "text-emphasis"
        - "text-emphasis-position"
        - "text-emphasis-style"
        - "text-emphasis-color"
        - "white-space"
        - "word-wrap"
        - "word-break"
        - "hyphens"
        - "word-spacing"
        - "letter-spacing"
        - "text-shadow"
        - "color"
        - "background-clip"
        - "background"
        - "background-color"
        - "background-image"
        - "background-attachment"
        - "background-repeat"
        - "background-position"
        - "background-size"
        - "background-blend-mode"
        - "mix-blend-mode"
        - "pointer-events"
        - "cursor"
        - "visibility"
        - "opaticy"
        - "transform-style"
        - "perspective"
        - "perspective-origin"
        - "transform"
        - "transform-origin"
        - "backface-visibility"
        - "filter"
        - "clip"
        - "clip-path"
        - "touch-action"
        - "will-change"
        - "animation"
        - "animation-play-state"
        - "animation-name"
        - "animation-delay"
        - "animation-duration"
        - "animation-iteration-count"
        - "animation-timing-function"
        - "animation-fill-mode"
        - "transition"
        - "transition-property"
        - "transition-delay"
        - "transition-duration"
        - "transition-timing-function"

        # columns, grid, mask...
